version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "9996:15672"
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "processdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "9997:5432"

  process:
    image: "docker.totvs.io/tjf/process-service-discriminator"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./definitions:/definitions
    ports:
      - "9998:8080"
    environment:
      serviceDiscriminatorDomainExchange: "domain-exchange"
      serviceDiscriminatorDBHost: "postgres/processdb"
      serviceDiscriminatorDBUser: "admin"
      serviceDiscriminatorDBPass: "admin"
      serviceDiscriminatorRabbitHost: "rabbitmq"
      serviceDiscriminatorRabbitUsername: "guest"
      serviceDiscriminatorRabbitPassword: "guest"

  sample:
    image: "node:9"
    depends_on:
      - process
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: bash -c "npm install && npm start"

volumes:
  rabbitmq-volume: