server:
  port: 8080

tjf:
  security:
    protected:
      include:
      - "/api/**"
#      - "/open/**"
    csrf:
      enable: false
    config:
      application-id: 839c1d973f6f4c0a9d0307e9cf7d3585
    access:
      api:
        permissions-uri: https://admin.rac.dev.totvs.app/totvs.rac/api/permissions
        jwk-uris:
        - https://admin.rac.dev.totvs.app/totvs.rac/.well-known/openid-configuration/jwks
