spring:
  datasource:
    url: jdbc:h2:file:~/h2db
    driverClassName: org.h2.Driver
    username: sa
    password: 
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

server:
  port: 8880
  
security:
  oauth2:
    resource:
      id: authorization_api
      jwk:
        key-set-uri: http://localhost:5009/totvs.rac/.well-known/openid-configuration/jwks
  