version: '3'

networks:
  docker-network:
    driver: host

services:

  amq:
    image: vromero/activemq-artemis:latest-alpine
    container_name: tjf-activemq
    networks:
      - docker-network
    environment:
      ARTEMIS_USERNAME: user-amq
      ARTEMIS_PASSWORD: password-amq
    ports:
      - 8161:8161
      - 61616:61616

