tjf:
  api:
    filter:
      fields:
        enabled: true

spring:

  application:
    name: sgdp-test-sample
  
  h2:
    console:
      enabled: true
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cash-account;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sa
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:      
      hibernate:
        format_sql: true

  cloud:
    stream:    
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:9092
          #brokers: localhost:9092
          configuration:
            auto:
              offset:
                reset: earliest    
      bindings:
        sgdp-kafka-reader:
          destination: sgdp-audit
          binder: kafka
        sgdp-audit:
          destination: sgdp-audit
          contentType: application/json
          binder: kafka
        tjf-messaging-error-input:
          destination: error-messaging
          group: errors
          binder: kafka
        tjf-messaging-error-output:
          destination: error-messaging
          group: errors
          producer:
            requiredGroups: errors
          binder: kafka     
          
server:
  port: 8180        
