server:
  port: 8082

spring:
  application:
    name: tjf-messaging-amqp-publisher

tjf:
  messaging:
    amqp:
      hostname: localhost
      username: admin
      password: totvs@123
      port: 5672
