spring:
  
  flyway:
    enabled: true

  # Configurações H2
  h2:
    console:
      enabled: true
      path: /h2

  # Configurações banco de dados
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:starwarsdb
    username: sa

  # Configurações JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        session_factory:
          statement_inspector: com.totvs.tjf.tenant.discriminator.SQLInspector