tjf:
  lscloud:
    module-id: "1234"
    group-id: "1234"
    slot-id: "1234"

spring:
  cloud:
    function:
      routing:
        enabled: true
      routing-expression: headers['type']
    stream:
      default-binder: rabbit1
 
      bindings:   
        lscloud-out-0:
          binder: rabbit1
          destination:  LogLicense.input
            
        functionRouter-in-0:
          binder: rabbit1
          destination: LogLicense.input.dlq

      binders:
        rabbit1:
          type: rabbit
      rabbit:
        default:
          exchangeType: headers
   

server:
  port: 8080
