tjf:
  lscloud:
    module-id: "1234"
    group-id: "1234"
    slot-id: "1234"

spring:
  cloud:
    function:
      routing:
        enabled: true
      routing-expression: headers['type']
    stream:
      pollable-source: tjf-messaging-error
      
      default-binder: rabbit1
 
      bindings:   
        lscloud-out-0:
          binder: rabbit1
          destination:  LogLicense
          group: input
          error-handler-definition: ErrorMessage
          producer:
            requiredGroups: input
            
        functionRouter-in-0:
          binder: rabbit1
          destination: LogLicense.input
          group: dlq
          error-handler-definition: ErrorMessage

    
      binders:
        rabbit1:
          type: rabbit
      rabbit:
        default:
          exchangeType: headers
   

server:
  port: 8080
